# Generated by Django 5.0 on 2024-01-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productquantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Completed'), (2, 'Deleted')], default=0),
        ),
    ]
